### ISSUE TITLE
Docker setup 懶人包

### ISSUE THREAD

**Issue by VdustR** [VdustR/assclub#3]
# Docker

請參考 [Docker 介紹](https://philipzheng.gitbooks.io/docker_practice/content/introduction/)。

## 安裝 docker

Linux 不要直接使用 distributions apt 或 yum 預設提供的版本，請參考[官方安裝教學](https://docs.docker.com/install/)。

## 調整 docker 工作目錄

如果遇到空間不足或其他特別需求可以透過下列修改方式改變 docker 工作目錄：

Create config directory and create a config file

```bash
sudo mkdir /etc/systemd/system/docker.service.d/
sudo nano /etc/systemd/system/docker.service.d/custom.conf
```

Contents of that file should be:

```text
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -g YOUR_DESIRED_DOCKER_IMAGE_ROOT_HERE
```

Restart docker service:

```bash
sudo systemctl daemon-reload
sudo systemctl restart docker
```

Remove original workspace:

```bash
# 注意是否正確
ll /var/lib/docker
# 確認沒錯再移除
rm -rf /var/lib/docker
```

- *[https://sanenthusiast.com/change-default-image-container-location-docker/](https://sanenthusiast.com/change-default-image-container-location-docker/)*
- *[https://gist.github.com/connormanning/26cea265bf81fdeae4e536e8afec936f](https://gist.github.com/connormanning/26cea265bf81fdeae4e536e8afec936f)*

## 調整 docker0 bridge

有時候我們會遇到網段衝突的問題，此時我們可以調整 docker default network interface:

```bash
vi /etc/docker/daemon.json
```

以下以 `10.253.0.1/16` 為例:

```text
{
  "bip": "10.253.0.1/16"
}
```

接著重啟服務：

```bash
sudo systemctl stop docker
sudo ip link delete docker0
sudo systemctl start docker
```

- *https://docs.docker.com/v17.09/engine/userguide/networking/default_network/custom-docker0/*

若使用 docker-compose 預設啟動一樣會先使用 `172.*.0.0/16` 網段，可選擇：

- 使用預設 bridge(`docker0`):

```yaml
version: '3'
services:
  myService:
    # ...
    network_mode: "bridge"
  anotherService:
    # ...
    network_mode: "bridge"
    links:
      - myService
```

- 指定其他網段:

```yaml
version: '3'
services:
  myService:
    # ...
  anotherService:
    # ...
network:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 10.252.0.0/16
```
