### ISSUE TITLE
Portainer.io setup 懶人包

### ISSUE THREAD

**Issue by VdustR** [VdustR/assclub#4]
# Portainer.io

[portainer.io](https://portainer.io/) 是一個 docker 的 Web GUI dashboard.

## 安裝

[portainer.io](https://portainer.io/) 官方有提供 [docker-compose](https://github.com/portainer/portainer-compose)。我們可以輕鬆地部署 portainer。

```bash
git clone git@github.com:portainer/portainer-compose.git
cd portainer-compose
```

接著我們可以輸入下列語法

```bash
vi ./docker-compose.yml
```

來調整一些設定，比如：

```yml
version: '2'

services:
  proxy:
    # ...
    ports:
#      修改 port
#      - "80:80"
      - "9999:80"
  portainer:
    # ...
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # 修改資料存放位置(不建議)
      # - /opt/portainer/data:/data
      - ./volumes/portainer/data:/data
networks:
  local:
    driver: bridge
    # 調整 network interface ip
    ipam:
     config:
       - subnet: 10.252.0.0/16
```

存檔後可執行以下指令啟動 docker container:

```bash
docker-compose up -d
```

接著請求 `http:/localhost/portainer`(視設定調整)即可進入初始畫面。輸入 admin 帳號密碼後選擇 local 即可。
