### ISSUE TITLE
GitLab setup 懶人包

### ISSUE THREAD

**Issue by VdustR** [VdustR/assclub#5]
# GitLab

## 安裝

使用 `docker-compose` 架設 GitLab 輕鬆愉快。

編輯 `docker-compose.yml`:

```yml
version: '3'

services:
  # 調整為自己想要的 local name
  gitlab:
    # 自訂 container name
    container_name: gitlab
    # 可選擇要使用的版本
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    # hostname, 建議架設在本地的話也不要直接使用 localhost，去 /etc/hosts 給個假域名，否則 runner 無法請求
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # protocol://hostname:port
        external_url 'http://localhost:8000'
        # Add any other gitlab.rb configuration here, each on its own line
        # 時區
        gitlab_rails['time_zone'] = 'Asia/Taipei'
        # ssh port
        gitlab_rails['gitlab_shell_ssh_port'] = 8002
    ports:
      # http port(注意會跟著 external_url 走，不會固定 80)
      - '8000:8000'
      # https port(注意會跟著 external_url 走，不會固定 443)
      - '8001:443'
      # ssh port, 跟著 gitlab_rails['gitlab_shell_ssh_port']
      - '8002:22'
    volumes:
      # data 存放位置
      - './volumes/gitlab/config:/etc/gitlab'
      - './volumes/gitlab/logs:/var/log/gitlab'
      - './volumes/gitlab/data:/var/opt/gitlab'
    network_mode: "bridge"
  gitlab-runner:
    container_name: gitlab-runner
    # 可選擇要使用的版本
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    volumes:
      # data 存放位置
      - './volumes/gitlab-runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    network_mode: "bridge"
    links:
      # 輸入 gitlab 的 container_name
      - gitlab
```

設定完成後即可啟動 docker container:

```bash
docker-composer up -d
```

## 備份

gitlab 開啟的狀況下執行:

```bash
docker exec -t gitlab gitlab-rake gitlab:backup:create
```

備份會存在: `data/backups/`。

### 使用 crontab 進行每日備份

新增 `backup.sh`:

```bash
#!/bin/bash
# 執行備份語法。請自行輸入 <name of container>
docker exec -t <name of container> gitlab-rake gitlab:backup:create
# 進入備份資料夾
cd /some/where/volumes/gitlab/data/backups
# 僅留最後三筆
ls -1tr | head -n -3 | xargs -d '\n' rm -f --
```

設定 `crontab`:

```bash
crontab -e
```

輸入並存檔:

```text
# minute   hour   day   month   dayofweek   command
0 3 * * * /some/where/gitlab/backup.sh
```

這樣每日凌晨三點就會自動執行備份了！

## 還原

啟動與備份檔版本相同的 gitlab docker 後，將還原檔放置於 backups 目錄 `/some/where/volumes/gitlab/data/backups`。

注意使用者權限，使用者必須和其他 docker 檔相同。

比如觀察到:

```bash
$ ll volumes/gitlab/data/backups/ -a
total 939M
drwx------.  2 libstoragemgmt 4.0K Jul 23 03:00 ./
drwxr-xr-x. 20 root           4.0K Jul 23 10:26 ../
-rw-------.  1 root           313M Jul 23 03:00 1532286025_2018_07_22_11.0.4_gitlab_backup.tar

# 調整 owner
chown libstoragemgmt volumes/gitlab/data/backups/1532286025_2018_07_22_11.0.4_gitlab_backup.tar
```

執行還原命令:

```bash
# 請自行輸入 <name of container>
docker exec -it <name of container> gitlab-rake gitlab:backup:restore
```

## GitLab / Discord Integration

在 discord 中 Server Setting -> Webhooks -> Create Webhook

複製 webhook URL:

```text
https://discordapp.com/api/webhooks/{webhook.id}/{webhook.token}
```

改為:

```text
https://skyhook.glitch.me/api/webhooks/{webhook.id}/{webhook.token}/gitlab
```

在 gitlab repository 中 Settings -> Integrations，將上述網址輸入 URL 並勾選需要通知之事件按下 Add webhook 即完成。

## Runner

執行命令:

```bash
# 請自行輸入 <name of runner container>
docker exec -it <name of runner container> gitlab-runner register

# 接著會進入互動式介面

Please enter the gitlab-ci coordinator URL (e.g. https://gitlab.com/):
# 看 docker-compose 裡面 link 怎麼打，protocol 和 port 對應 external_url
http://gitlab:8000

Please enter the gitlab-ci token for this runner:
# 從 gitlab repo CI/CD 或 admin runner 的設定可以找到 registration token

Please enter the gitlab-ci description for this runner:

[d3b8b2b5c238]:
# 輸入一個人類可辨識的名稱
Please enter the gitlab-ci tags for this runner (comma separated):

Please enter the executor: docker-ssh, docker-ssh+machine, virtualbox, docker+machine, kubernetes, docker, parallels, shell, ssh:
# 這裡我們目前都使用 docker
docker

Please enter the default Docker image (e.g. ruby:2.1):
# 輸入我們要執行的環境
node:latest
```

調整完後我們需要讓 runner 生出來的 docker container 也連得到 gitlab:

```bash
vi /some/where/volumes/gitlab-runner/config/config.toml
```

```toml
# ...
  [runners.docker]
    # ...
    # 輸入 gitlab container name
    links = ["gitlab"]
    # 使用 local only image 的話不要 pull
    pull_policy = "never"
    volumes = [
      # 必須設定一個 directory 使 cache 得以在不同 stage 間傳遞
      # 檔案也會在不同 pipelines 或 repository 間保留
      # 因此若要測試 dependencies 設定建議在 pipeline 的開頭先將 modules 清空
      # 建議一個 runner 一個獨立的資料夾
      "/tmp/docker/gitlab-runner/cache/group-name:/cache",

      # 使用與 server 相同的 .ssh 設定，或是可以使用自己的 ssh key

      # linux deploy user(suggested)
      "/home/username/.ssh/id_rsa:/root/.ssh/id_rsa:ro"

      # linux root
      "/root/.ssh/id_rsa:/root/.ssh/id_rsa:ro"

      # mac user
      "/Users/username/.ssh/id_rsa:/root/.ssh/id_rsa:ro"

      # 部署到 host 上可以 mount directory
      "/service/on/host:/deploy/in/container"
    ]
  [runners.cache]
```

若使用 rsync -e ssh 部署到遠端機器，機器上需將 deploy 帳號的 `id_rsa.pub` 複製到 `authorized_key`:

```bash
vi /home/username/.ssh/authorized_key
vi /Users/username/.ssh/authorized_key
vi /root/.ssh/authorized_key
```

> 重新設定 `config.toml` **不需要** 重新啟動 gitlab 或 gitlab runner。

設定完成後 `gitlab-ci.yml` 即可在 `script` section 使用 rsync 下deploy。

遠端:

```yml
deploy:
  script:
    # ...
    - rsync -avh -e ssh --delete ./dist/ /deploy/in/container
    # non standard port
    - rsync -avh -e 'ssh -p 8080' --delete ./dist/ deploy@host.deploy.to:/deploy/in/container
```

本機:

```yml
deploy:
  script:
    # ...
    - rsync -avh --delete ./dist/ /deploy/in/container
```
